### PR TITLE
MAINT: linalg: clean-up for `flinalg` removal

### PR DESCRIPTION
**Pull request by lucascolley**
This covers all of the occurrences of "flinalg" in the repo apart from https://github.com/scipy/scipy/blob/e00a5948a9dddd81954d2039d71e7b0ffe8a36bc/scipy/linalg/_basic.py#L947-L955 ; do you want to remove that or should it stay?

### CODE REVIEW

**Comment by ilayn** [comment]
All looks good to me, please feel free to merge if you can otherwise I can too

**Review by ilayn — APPROVED** [review]

**Comment by lucascolley** [comment]
I think only you can merge

**Comment by ilayn** [comment]
Done

**Comment by ilayn** [comment]
We can handle the commented section in the actual PR

**Pull request merged**
